### ISSUE TITLE
Error when connection to remote Redshift cluster

### ISSUE THREAD

**Issue by jasonstrimpel** [opendatadiscovery/odd-platform#1086]
**Describe the bug**
(A clear and concise description of what the bug is.)

When attempting to connect to a remote Redshift cluster, I receive the following exception:

```
odd-collector_1          | Traceback (most recent call last):
odd-collector_1          |   File "/app/odd_collector/adapters/redshift/adapter.py", line 90, in __connect
odd-collector_1          |     self.__connection = psycopg2.connect(self._data_source)
odd-collector_1          |   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
odd-collector_1          |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
odd-collector_1          | psycopg2.OperationalError: could not translate host name "my.redshift.cluster" to address: Name or service not known
```

**Set up**
(How do you run the app?
Which version of the app are you running? Provide either docker image version or check commit hash at the top left corner. We won't be able to help you without this information.)

I followed the instructions [here](https://github.com/opendatadiscovery/odd-platform).

My `collector_config.yaml` file looks like this:

```
default_pulling_interval: 1
token: "MGnOJf0ni9fZW4wHkzOxoaOtkYt5op8vts567pTX"
plugins:
  - type: postgresql
    name: postgresql-step2-test
    host: !ENV ${SAMPLE_POSTGRES_HOST}
    port: 5432
    database: !ENV ${SAMPLE_POSTGRES_DATABASE}
    user: !ENV ${SAMPLE_POSTGRES_USER}
    password: !ENV ${SAMPLE_POSTGRES_PASSWORD}
  - type: redshift
    name: My Redshift Cluster
    description: "" # Optional string
    database: prod
    host: my.redshift.cluster
    port: 8192
    user: username
    password: password
```

**Steps to Reproduce**

I followed the instructions [here](https://github.com/opendatadiscovery/odd-platform).

**Expected behavior**
(A clear and concise description of what you expected to happen)

A connection to the cluster is opened successfully and the meta data is populated.

**Screenshots**
(If applicable, add screenshots to help explain your problem)

NA.

**Additional context**
(Add any other context about the problem here)
