### ISSUE TITLE
Duplicate DataSetField oddrns while ingesting from Hive

### ISSUE THREAD

**Issue by bigdata-spec** [opendatadiscovery/odd-platform#1202]
Hi，I meet someting wrong with catalog：
```
collector_config.yaml
platform_host_url: http://192.168.56.118:8089
default_pulling_interval: 3
token: "kb3kd5OgoftyHIOe13vNCndaODo3im5sCN8LtBVi"
plugins:
  - type: hive
    name: hive_adapter_zone_ads
    host: 10.131.122.15
    port: 9083
    database: zone_ads
```
because 8080 is used，so I use 8089 for odd-platform，
I run **docker-compose -f docker/demo.yaml restart odd-collector**
![image](https://user-images.githubusercontent.com/23710717/210330154-4c035ab2-6b4b-4f08-8d12-6a7606067d49.png)

and there is no data in catalog，
![image](https://user-images.githubusercontent.com/23710717/210330392-c2bdbb3f-18d8-4d42-a176-e64bc14424da.png)
