### ISSUE TITLE
Adding Login to demo docker removes the existing datasources

### ISSUE THREAD

**Issue by manugarri** [opendatadiscovery/odd-platform#1414]
Running the docker example as defined in the readme:

`docker-compose -f docker/demo.yaml up -d odd-platform-enricher`

and navigating to the localhost:8080 will show all of the demo catalog:
![image](https://github.com/opendatadiscovery/odd-platform/assets/3670355/bb8b1ed3-b625-40d5-a3db-3adf0434cf2e)

However, adding user/password authentication by adding to the `demo.yaml` the following:
```
  odd-platform:
    image: ghcr.io/opendatadiscovery/odd-platform:latest
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${POSTGRES_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - AUTH_TYPE=LOGIN_FORM
```

and running docker-compose with the same command as above, means the url localhost:8080 shows an empty catalog:
![image](https://github.com/opendatadiscovery/odd-platform/assets/3670355/8a96d49a-6dd6-4126-aa9c-ff88582e5499)
