### ISSUE TITLE
Cannot connect to ODD Platform after configuring Azure Identity Provider

### ISSUE THREAD

**Issue by babaMar** [opendatadiscovery/odd-platform#1712]
**Describe the bug**
The platform keeps returning **Invalid Credentials**

**Set up**
Deployed via Helm, latest chart version. Configuration for Azure provider:

```    
    auth:
      type: OAUTH2
      oauth2:
        client:
          azure:
            provider: 'azure'
            azure-tenant-id: "$(AZURE_TENANT_ID)"
            client-id: "$(OddPlatformAzureAuthClientId)"
            client-secret: "$(OddPlatformAzureAuthClientSecret)"
            client-name: azure
            redirect-uri: "https://datagovernance$(NewGlobeGlobalHostNameSuffix)/login/oauth2/code/azure"
            scope:
              - openid
              - offline_access
              - https://graph.microsoft.com/user.read
            authorization-uri: https://login.microsoftonline.com/${auth.oauth2.client.azure.azure-tenant-id}/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/${auth.oauth2.client.azure.azure-tenant-id}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            user-name-attribute: email
            admin-attribute: email
            admin-principals:
              - stefano.messina@uat.newglobe.education
```

**Expected behavior**
Able to login

**Screenshots**
![odd-access](https://github.com/user-attachments/assets/3da202d5-23ec-4306-acb8-8b856435f234)

**Additional Context**
My Azure credentials are correct, as I'm able to login to all other services in our organization.
